dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev
  - sudo apt-get -y install bc nano patch mosquitto
  - sudo apt-get -y install libelf-dev sparse flawfinder
  - sudo apt-get -y install libedit-dev
  - sudo apt-get -y install coccinelle

before_script:
  - make prepare_kernel
  - make patch
  - make config_travis

script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  - make compile_security
  - make compile_kernel
  - make test_travis

after_success:
  - make prepare_release_travis
  - make prepare_git
  - make patch_git
  - make update_linuxkit
  - cd ./build/linuxkit
  - git remote add to_push https://${GITHUB_KEY}@github.com/crimson-unicorn/output.git > /dev/null 2>&1
  - git pull --allow-unrelated-histories
  - git push --set-upstream to_push master

deploy:
  provider: releases
  api_key: "$GITHUB_KEY"
  file:
    - patch
  skip_cleanup: true
  on:
    tags: true

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
