version: 2.1
jobs:
  checkout:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'make prepare_kernel'
      - save_cache:
          key: v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circulate
  doc:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - restore_cache:
          keys:
            - v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'cd ./scripts && make prepare'
      - run: 'cd ./scripts && make config'
      - run:
          command: 'cd ./scripts && make compile'
          no_output_timeout: '30m'
      - run: 'cd ./scripts && make run'
      - run: 'cd ./scripts && cat syslist.txt'
      - run: 'make doc'
      - save_cache:
          key: v1-doc-scripts-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circulate/scripts
      - save_cache:
          key: v1-doc-docs-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circulate/docs
  sparse:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - restore_cache:
          keys:
            - v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install -y sparse'
      - run: 'apt-get install --reinstall make'
      - run: 'make sparse'
      - run: 'cat ./test/sparse.txt'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - doc:
          requires:
            - checkout
      - sparse:
          requires:
            - checkout
