version: 2.1
jobs:
  checkout:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'make prepare_kernel'
      - save_cache:
          key: v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circulate
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - restore_cache:
          keys:
            - v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
      - run: 'echo 1'
  test:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - restore_cache:
          keys:
            - v1-prepare-{{ .Environment.CIRCLE_SHA1 }}
      - run: 'echo 2'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
