version: 2
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - run:
          name: update
          command: 'apt-get update -qq'
      - run:
          name: sudo
          command: 'apt-get install -y sudo'
      - run:
          name: dependencies
          command: 'apt-get install -y build-essential autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run:
          name: reinstall-make
          command: 'apt-get install --reinstall make'
      - run:
          name: prepare-analysis
          command: 'cd ./analysis && make prepare'
      - run:
          name: prepare-kernel
          command: 'make prepare_kernel'
      - run:
          name: config
          command: 'cd ./analysis && make config'
