version: 2
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    environment:
      - SOURCE_BRANCH: dev
      - TARGET_BRANCH: dev
    steps:
      - checkout
      - run:
          name: update
          command: 'apt-get update -qq'
      - run:
          name: sudo
          command: 'apt-get install -y sudo'
      - run:
          name: dependencies
          command: 'apt-get install -y build-essential python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run:
          name: reinstall-make
          command: 'apt-get install --reinstall make'
      - run:
          name: prepare-analysis
          command: 'cd ./analysis && make prepare'
      - run:
          name: prepare-kernel
          command: 'make prepare_kernel'
      - run:
          name: config
          command: 'cd ./analysis && make config'
      - run:
          name: compile
          command: 'cd ./analysis && make compile'
      - run:
          name: analyse
          command: 'cd ./analysis && make run'
      - run:
          name: syslist
          command: 'cd ./scripts && cat syslist.txt'
      - run:
          name: syshooks
          command: 'cd ./scripts && cat syshooks.txt'
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              git commit -m "CircleCI automated documentation generation: ${CIRCLE_SHA1}"
              git push
            fi
