version: 2.1
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    steps:
      - checkout
      - run: 'echo 1'
  test:
    docker:
      - image: moul/kernel-builder:latest
    steps:
      - checkout
      - run: 'echo 2'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
