version: 2.1
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    environment:
      - SOURCE_BRANCH: dev
      - TARGET_BRANCH: dev
    steps:
      - checkout
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'cd ./scripts && make prepare'
      - run: 'make prepare_kernel'
      - run: 'cd ./scripts && make config'
      - run: 'cd ./scripts && make compile'
          no_output_timeout: '30m'
      - run: 'cd ./scripts && make run'
      - run: 'cd ./scripts && cat syslist.txt'
      - run: 'cd ./scripts && cat syshooks.txt'
      - run: 'make doc'
  test:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    environment:
      - SOURCE_BRANCH: dev
      - TARGET_BRANCH: dev
    steps:
      - checkout
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'make prepare_kernel'
      - run: 'echo 1'
workflows:
  version: 2
  myjob:
    - build
    - test
